### ISSUE TITLE
The code do not run successfully, can you help me?

### ISSUE THREAD

**Issue by zhymma** [esteng/regal_program_learning#2]
Traceback (most recent call last):
  File "/data/zhyma/code/regal_program_learning-main/regal_program_learning-main/program_refactoring/refactor_db.py", line 83, in gpt_resolve
    tree.recursive_resolve(log_dir_to_run,
  File "/data/zhyma/code/regal_program_learning-main/regal_program_learning-main/program_refactoring/tree/big_tree.py", line 297, in recursive_resolve
    with open(existing_log_dir / "node_dict.pkl", 'rb') as f1:
FileNotFoundError: [Errno 2] No such file or directory: '/data/zhyma/code/regal_program_learning-main/regal_program_learning-main/logs/experiment_2024-05-14_17_02_task_python_dataset_date_refactor_5_filter_5_redo_done_False_comments_False_helpers_second_True/node_dict.pkl'

**Comment by esteng** [comment]
This looks like a path issue -- hard to resolve without knowing more about your setup/paths. Are you sure that the `logs` directory exists?
