### ISSUE TITLE
Dataflow Module not found

### ISSUE THREAD

**Issue by Tsesterh** [esteng/regal_program_learning#3]
Hello,
first of all, thanks for sharing your work!

I am trying to make the repository running, but I get an issue when executing /scripts/date/train_regal.sh after the preprocess.sh script ran perfectly:

Traceback (most recent call last):
  File "/home/tobi/Dokumente/regal_program_learning/program_refactoring/refactor_db.py", line 14, in <module>
    from program_refactoring.tree.big_tree import BiggerTree 
  File "/home/tobi/Dokumente/regal_program_learning/program_refactoring/tree/big_tree.py", line 13, in <module>
    from program_refactoring.tree.tuple import Tuple
  File "/home/tobi/Dokumente/regal_program_learning/program_refactoring/tree/tuple.py", line 7, in <module>
    from program_refactoring.tree.node import Node
  File "/home/tobi/Dokumente/regal_program_learning/program_refactoring/tree/node.py", line 10, in <module>
    from dataflow.core.lispress import (parse_lispress,
ModuleNotFoundError: No module named 'dataflow'

I installed the dataflow module using pip install dataflow, but then there is a new error:

Traceback (most recent call last):
  File "/home/tobi/Dokumente/regal_program_learning/program_refactoring/refactor_db.py", line 14, in <module>
    from program_refactoring.tree.big_tree import BiggerTree 
  File "/home/tobi/Dokumente/regal_program_learning/program_refactoring/tree/big_tree.py", line 13, in <module>
    from program_refactoring.tree.tuple import Tuple
  File "/home/tobi/Dokumente/regal_program_learning/program_refactoring/tree/tuple.py", line 7, in <module>
    from program_refactoring.tree.node import Node
  File "/home/tobi/Dokumente/regal_program_learning/program_refactoring/tree/node.py", line 10, in <module>
    from dataflow.core.lispress import (parse_lispress,
ModuleNotFoundError: No module named 'dataflow.core'

Any ideas how to solve this? I am using Python 3.9.

Thanks!

**Comment by esteng** [comment]
Hi, 
That import actually has to do with experiments we ran on the SMCalFlow dataset which we didn't end up using in the final version. AFAICT the issue looks like a version issue with the dataflow library, which supports that dataset. I believe we ended up installing dataflow from their github rather than pip. 

Unless you are planning on running on CalFlow, you should be able to comment out references to the dataflow library without breaking anything in the remaining codebase.
